apiVersion: v1
kind: Service
metadata:
  name: chartmuseum
  namespace: kube-system
  labels:
    app: chartmuseum
spec:
  {{- template "chartmuseum.service.ports" }}
  selector:
    app: chartmuseum
  type: ClusterIP